#!/bin/bash
##=============================================================================##
 # SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0                       #
 # Nordix license - https://polyformproject.org/licenses/noncommercial/1.0.0  #
 # Copyright (c) 2025 Jimmy Källhagen                                          #
 # Part of Nordix - https://github.com/jimmykallhagen/Nordix                   #
 # Nordix and Yggdrasil are trademarks of Jimmy Källhagen                      #
##=============================================================================##
cores=$(($(nproc) / 2))
for ((i=0; i<cores; i++)); do
    printf "Core %2d:  %2d - %2d\n" "$i" "$i" "$((i + cores))"
done
