#!/bin/bash
##========================================================##
 # SPDX-License-Identifier: GPL-3.0-or-later              #
 # Copyright (c) 2025 Jimmy Källhagen                     #
 # Part of Yggdrasil - Nordix desktop environment         #
 # Nordix and Yggdrasil are trademarks of Jimmy Källhagen # 
##========================================================##

# nordix-vm-bridge - Activate/Remove VM-bridge

if nmcli connection show "Nordix Bridge" &>/dev/null; then
    echo "Bridge already exist, du you want to delete it? [Y/N]"
    read -r response
    if [[ "$response" =~ ^[Yy]$ ]]; then
        sudo nmcli connection down "Nordix Bridge" 2>/dev/null
        sudo nmcli connection delete "Nordix Bridge"
        sudo nmcli connection delete "Bridge-Slave" 2>/dev/null
        sudo nmcli connection up "Wired connection 1"
        echo "[OK] Bridge removed"
    fi
else
    echo "Create VM-bridge..."
    ETHERNET=$(nmcli -t -f DEVICE,TYPE device | grep ethernet | cut -d: -f1 | head -1)
    
    sudo nmcli connection add type bridge ifname br0 con-name "Nordix Bridge"
    sudo nmcli connection add type bridge-slave ifname "$ETHERNET" master br0 con-name "Bridge-Slave"
    
# DNS settings on the bridge
    sudo nmcli connection modify "Nordix Bridge" ipv4.ignore-auto-dns yes
    sudo nmcli connection modify "Nordix Bridge" ipv4.dns "94.140.14.14 94.140.15.15"
    
    sudo nmcli connection down "Wired connection 1" 2>/dev/null
    sudo nmcli connection up "Nordix Bridge"
    
    echo "VM bridge enabled!"
    echo "VM's can now use br0 for direct network access"
fi